Disable bindings on x86_64-debian-dylib builder
llvm/llvm-zorg pull request #19
Opened 2021-10-04 14:26 UTC by tbaederr

The tests for the OCaml bindings fail when using the llvm.so dylib.

@gribozavr Does this look right to you?

2021-10-04 15:36 UTC, gribozavr approved these changes

2021-10-04 15:37 UTC, gribozavr requested changes
Are you editing the right builder? It is not `x86_64-debian-dylib`.

2021-10-05 05:50 UTC, tbaederr commented
You are right of course, sorry. Fixed that.

2021-10-05 12:48 UTC, gribozavr approved these changes
Do you have permissions to merge?

2021-10-05 14:27 UTC, merged