Add new arguments for UnifiedBuildTree.getCmakeExBuildFactory() factory.
llvm/llvm-zorg pull request #224
Opened 2024-07-10 06:10 UTC by vvereschaka

* repo_profiles - pass a repository profile name ("default") to retrieve the source code or pass None to disable checking out from the repos.
* hint - factory hint.

Both of those new arguments are useful for the nested factories.

Also removed usage of IRenderable/Interpolate on the arguments inside of the factory. The arguments can be IRenderable and we must not wrapping them in IRenderable again.

2024-07-10 06:11 UTC, vvereschaka commented
depends on #223

2024-07-11 18:56 UTC, gkistanova requested changes
I see 3 unrelated changes in this PR. Could you split them to 3 separate PRs, please?

One for the "hint", another one for "repo_profiles" (why that's plural, by the way?), and the third one for deleting the "Remove the source code" step.

Thanks!

2024-07-11 19:22 UTC, vvereschaka commented
It could be difficult to split these changes for 3 commits. The changes are too close. Is it really necessary?

>another one for "repo_profiles" (why that's plural, by the way?)

 I'm thinking may be in future it would be simpler to switch to multiply profiles to allow builder getting the source code (or something else) from multiply sources. We can do it without changing the argument name.

2024-07-11 19:54 UTC, vvereschaka commented
>Could you split them to 3 separate PRs, please?

ok

2024-07-11 19:54 UTC, closed without merging