Add a new build factory to create the staged builders (StagedBuilder).
llvm/llvm-zorg pull request #41
Opened 2023-09-05 20:38 UTC by vvereschaka

* StagedBuilder.getCmakeBuildFactory

The factory provides a staged builder configuration to build the LLVM project unified tree.

2023-09-05 20:59 UTC, vvereschaka commented
An example of the builder configuration with this build factory can be found here https://github.com/llvm/llvm-zorg/pull/42

2023-09-06 06:39 UTC, petrhosek commented
This seems to be replicating a lot of the existing logic that already exists inside the LLVM bootstrapping and runtimes build. Would it be possible to use the existing build support (improving it where needed) instead?

2023-09-13 03:24 UTC, vvereschaka commented
This factory actually a replacement for `UnifiedTreeBuilder.getCmakeWithNinjaMultistageBuildFactory`, `FlangBuilder.getFlangOutOfTreeBuildFactory`, flang tuntime and any other factories for the **simple** staged builders.
The clang/bootstrap build factories are too specific and complicated currently and they cannot be used for the simple staged builds.

2023-09-26 22:13 UTC, gkistanova requested changes
Thanks for the patch, Vlad!

Could you address a few things, please?

Plus I feel like I must be missing something with your `normalize_factory`, thus a few questions.

2023-09-26 22:13 UTC, gkistanova commented on zorg/buildbot/builders/StagedBuilder.py
> +        rf.enable_projects = f.depends_on_projects.difference(f.enable_runtimes)
Why does it depend on `f`?

2023-09-27 03:15 UTC, vvereschaka commented
@gkistanova I have updated this PR with the following changes (in additional to your change requests):
* fixed step names;
* guards for the max step names (48 characters +2 for BB identical name counters) (db limitation);
* multiple install targets for each stage;
* added properly formatted function's help/description;

2023-09-27 03:45 UTC, gkistanova approved these changes
LGTM.

2023-09-27 15:58 UTC, slydiman approved these changes
LGTM

2023-09-28 19:37 UTC, merged